# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Gerador(object):
    def setupUi(self, Gerador):
        Gerador.setObjectName("Gerador")
        Gerador.resize(1217, 690)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        Gerador.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Icons/Icon_5G.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Gerador.setWindowIcon(icon)
        Gerador.setStyleSheet("background-color: rgb(45, 45, 45);")
        Gerador.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(Gerador)
        self.centralwidget.setMinimumSize(QtCore.QSize(900, 615))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1351, 741))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("border: 0;\n"
"color: rgb(238, 238, 236);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tab.setStyleSheet("QPushButton#pushButtonVoip:pressed {\n"
"    background-color: rgba(115, 115, 115,255);\n"
"}\n"
"\n"
"QPushButton#pushButtonVoip {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.460227, y1:0, x2:0.483, y2:0.994318, stop:0.204545 rgba(115, 115, 115, 255), stop:0.755682 rgba(205, 205, 205, 255));\n"
"}\n"
"\n"
"border: 0;")
        self.tab.setObjectName("tab")
        self.pushButtonVoip = QtWidgets.QPushButton(self.tab)
        self.pushButtonVoip.setGeometry(QtCore.QRect(60, 240, 181, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonVoip.setFont(font)
        self.pushButtonVoip.setStyleSheet("border-radius:5px;\n"
"border:1px solid rgb(255, 255, 255)\n"
"")
        self.pushButtonVoip.setObjectName("pushButtonVoip")
        self.analiseEstatVoIP = QtWidgets.QWidget(self.tab)
        self.analiseEstatVoIP.setGeometry(QtCore.QRect(40, 300, 231, 221))
        self.analiseEstatVoIP.setObjectName("analiseEstatVoIP")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.analiseEstatVoIP)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 231, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(245,245,245);")
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(245,245,245);")
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.mediaViewVoIP = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.mediaViewVoIP.setFont(font)
        self.mediaViewVoIP.setStyleSheet("color: rgb(245,245,245)")
        self.mediaViewVoIP.setObjectName("mediaViewVoIP")
        self.verticalLayout.addWidget(self.mediaViewVoIP)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(245,245,245);")
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.desvioViewVoIP = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.desvioViewVoIP.setFont(font)
        self.desvioViewVoIP.setStyleSheet("color: rgb(245,245,245)")
        self.desvioViewVoIP.setObjectName("desvioViewVoIP")
        self.verticalLayout.addWidget(self.desvioViewVoIP)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(245,245,245);")
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.tempoTotalViewVoip = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.tempoTotalViewVoip.setFont(font)
        self.tempoTotalViewVoip.setStyleSheet("color: rgb(245,245,245)")
        self.tempoTotalViewVoip.setObjectName("tempoTotalViewVoip")
        self.verticalLayout.addWidget(self.tempoTotalViewVoip)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(245,245,245);")
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.hurstParameterVoIP = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.hurstParameterVoIP.setFont(font)
        self.hurstParameterVoIP.setStyleSheet("color: rgb(245,245,245)")
        self.hurstParameterVoIP.setObjectName("hurstParameterVoIP")
        self.verticalLayout.addWidget(self.hurstParameterVoIP)
        self.widgetVoIPPlot = QtWidgets.QWidget(self.tab)
        self.widgetVoIPPlot.setGeometry(QtCore.QRect(290, 40, 921, 481))
        self.widgetVoIPPlot.setObjectName("widgetVoIPPlot")
        self.comboBox_2 = QtWidgets.QComboBox(self.widgetVoIPPlot)
        self.comboBox_2.setGeometry(QtCore.QRect(0, 60, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setAutoFillBackground(False)
        self.comboBox_2.setStyleSheet("border-top-left-radius: 10px;\n"
"color: rgb(43, 43, 43);\n"
"background-color: rgb(177, 177, 177);\n"
"")
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox = QtWidgets.QComboBox(self.widgetVoIPPlot)
        self.comboBox.setEnabled(True)
        self.comboBox.setGeometry(QtCore.QRect(10, 120, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.comboBox.setStyleSheet("border-top-left-radius: 10px;\n"
"background-color: rgb(177, 177, 177);\n"
"color: rgb(45, 45, 45);")
        self.comboBox.setEditable(False)
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.widgetVoIPPlot)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(140, 0, 781, 481))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.voipPlotLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.voipPlotLayout_2.setContentsMargins(0, 0, 0, 0)
        self.voipPlotLayout_2.setObjectName("voipPlotLayout_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 50, 221, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.parametroVoIP = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.parametroVoIP.setContentsMargins(0, 0, 0, 0)
        self.parametroVoIP.setObjectName("parametroVoIP")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(245,245,245);")
        self.label.setObjectName("label")
        self.parametroVoIP.addWidget(self.label)
        self.duracao = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.duracao.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.duracao.sizePolicy().hasHeightForWidth())
        self.duracao.setSizePolicy(sizePolicy)
        self.duracao.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.duracao.setFont(font)
        self.duracao.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(45,45,45);\n"
"border-radius: 3px;\n"
"")
        self.duracao.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.duracao.setPlaceholderText("Duração")
        self.duracao.setObjectName("duracao")
        self.parametroVoIP.addWidget(self.duracao)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(245,245,245);\n"
"")
        self.label_14.setObjectName("label_14")
        self.parametroVoIP.addWidget(self.label_14)
        self.numeroCargasVoIP = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.numeroCargasVoIP.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numeroCargasVoIP.sizePolicy().hasHeightForWidth())
        self.numeroCargasVoIP.setSizePolicy(sizePolicy)
        self.numeroCargasVoIP.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.numeroCargasVoIP.setFont(font)
        self.numeroCargasVoIP.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(45, 45, 45);\n"
"border-radius: 3px;")
        self.numeroCargasVoIP.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.numeroCargasVoIP.setPlaceholderText("Digite o número de cargas")
        self.numeroCargasVoIP.setObjectName("numeroCargasVoIP")
        self.parametroVoIP.addWidget(self.numeroCargasVoIP)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("QPushButton#pushButtonStreamOD:pressed {\n"
"    background-color: rgba(115, 115, 115,255);\n"
"}\n"
"\n"
"QPushButton#pushButtonStreamOD {\n"
"    background-color: qlineargradient(spread:pad, x1:0.460227, y1:0, x2:0.483, y2:0.994318, stop:0.204545 rgba(115, 115, 115, 255), stop:0.755682 rgba(205, 205, 205, 255));\n"
"}\n"
"\n"
"border: 0;")
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(60, 30, 221, 211))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.parametrosVideo = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.parametrosVideo.setContentsMargins(0, 0, 0, 0)
        self.parametrosVideo.setObjectName("parametrosVideo")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(245, 245, 245);\n"
"")
        self.label_2.setObjectName("label_2")
        self.parametrosVideo.addWidget(self.label_2)
        self.comboBox_3 = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.comboBox_3.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("border-top-left-radius: 10px;\n"
"color: rgb(43, 43, 43);\n"
"background-color: rgb(177, 177, 177);\n"
"")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.parametrosVideo.addWidget(self.comboBox_3)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(245, 245, 245);")
        self.label_3.setObjectName("label_3")
        self.parametrosVideo.addWidget(self.label_3)
        self.tempoVideo = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.tempoVideo.setEnabled(True)
        self.tempoVideo.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.tempoVideo.setFont(font)
        self.tempoVideo.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(45,45,45);\n"
"border-radius: 3px;\n"
"")
        self.tempoVideo.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.tempoVideo.setPlaceholderText("Tempo de vídeo em segundos")
        self.tempoVideo.setObjectName("tempoVideo")
        self.parametrosVideo.addWidget(self.tempoVideo)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(245, 245, 245);\n"
"")
        self.label_5.setObjectName("label_5")
        self.parametrosVideo.addWidget(self.label_5)
        self.numeroCargas = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.numeroCargas.setEnabled(True)
        self.numeroCargas.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.numeroCargas.setFont(font)
        self.numeroCargas.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(45,45,45);\n"
"border-radius: 3px;\n"
"")
        self.numeroCargas.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.numeroCargas.setPlaceholderText("Tempo de vídeo em segundos")
        self.numeroCargas.setObjectName("numeroCargas")
        self.parametrosVideo.addWidget(self.numeroCargas)
        self.widget_2 = QtWidgets.QWidget(self.tab_2)
        self.widget_2.setGeometry(QtCore.QRect(350, 50, 811, 481))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.widget_2)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(140, 0, 671, 481))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.streamPlotLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.streamPlotLayout.setContentsMargins(0, 0, 0, 0)
        self.streamPlotLayout.setObjectName("streamPlotLayout")
        self.escalaStreamOD = QtWidgets.QComboBox(self.widget_2)
        self.escalaStreamOD.setGeometry(QtCore.QRect(0, 50, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.escalaStreamOD.setFont(font)
        self.escalaStreamOD.setStyleSheet("border-top-left-radius: 10px;\n"
"color: rgb(43, 43, 43);\n"
"background-color: rgb(177, 177, 177);\n"
"")
        self.escalaStreamOD.setObjectName("escalaStreamOD")
        self.escalaStreamOD.addItem("")
        self.escalaStreamOD.addItem("")
        self.escalaStreamOD.addItem("")
        self.numeroCarga = QtWidgets.QComboBox(self.widget_2)
        self.numeroCarga.setGeometry(QtCore.QRect(10, 110, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.numeroCarga.setFont(font)
        self.numeroCarga.setStyleSheet("border-top-left-radius: 10px;\n"
"color: rgb(43, 43, 43);\n"
"background-color: rgb(177, 177, 177);\n"
"")
        self.numeroCarga.setObjectName("numeroCarga")
        self.analiseEstatStreamOD = QtWidgets.QWidget(self.tab_2)
        self.analiseEstatStreamOD.setGeometry(QtCore.QRect(60, 320, 221, 221))
        self.analiseEstatStreamOD.setObjectName("analiseEstatStreamOD")
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.analiseEstatStreamOD)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(0, 0, 221, 221))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(245,245,245);")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(245,245,245);")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.mediaViewStreamOD = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.mediaViewStreamOD.setFont(font)
        self.mediaViewStreamOD.setStyleSheet("color: rgb(245,245,245)")
        self.mediaViewStreamOD.setObjectName("mediaViewStreamOD")
        self.verticalLayout_2.addWidget(self.mediaViewStreamOD)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(245,245,245);")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_2.addWidget(self.label_18)
        self.desvioViewStreamOD = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.desvioViewStreamOD.setFont(font)
        self.desvioViewStreamOD.setStyleSheet("color: rgb(245,245,245)")
        self.desvioViewStreamOD.setObjectName("desvioViewStreamOD")
        self.verticalLayout_2.addWidget(self.desvioViewStreamOD)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(245,245,245);")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.tempoTotalViewStreamOD = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.tempoTotalViewStreamOD.setFont(font)
        self.tempoTotalViewStreamOD.setStyleSheet("color: rgb(245,245,245)")
        self.tempoTotalViewStreamOD.setObjectName("tempoTotalViewStreamOD")
        self.verticalLayout_2.addWidget(self.tempoTotalViewStreamOD)
        self.label_28 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(245,245,245);")
        self.label_28.setObjectName("label_28")
        self.verticalLayout_2.addWidget(self.label_28)
        self.hurstParameterStreamOD = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.hurstParameterStreamOD.setFont(font)
        self.hurstParameterStreamOD.setStyleSheet("color: rgb(245,245,245)")
        self.hurstParameterStreamOD.setObjectName("hurstParameterStreamOD")
        self.verticalLayout_2.addWidget(self.hurstParameterStreamOD)
        self.pushButtonStreamOD = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonStreamOD.setGeometry(QtCore.QRect(70, 260, 181, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonStreamOD.setFont(font)
        self.pushButtonStreamOD.setStyleSheet("border-radius:5px;\n"
"border:1px solid rgb(255, 255, 255);")
        self.pushButtonStreamOD.setObjectName("pushButtonStreamOD")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tab_3.setFont(font)
        self.tab_3.setStyleSheet("QPushButton#pushButtonWeb:pressed {\n"
"    background-color: rgba(115, 115, 115,255);\n"
"}\n"
"\n"
"QPushButton#pushButtonWeb {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.460227, y1:0, x2:0.483, y2:0.994318, stop:0.204545 rgba(115, 115, 115, 255), stop:0.755682 rgba(205, 205, 205, 255));\n"
"}\n"
"\n"
"border: 0;")
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(30, 50, 322, 151))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.parametrosWeb = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.parametrosWeb.setContentsMargins(0, 0, 0, 0)
        self.parametrosWeb.setObjectName("parametrosWeb")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(245, 245, 245);")
        self.label_4.setObjectName("label_4")
        self.parametrosWeb.addWidget(self.label_4)
        self.tempoCargaWeb = QtWidgets.QTextEdit(self.verticalLayoutWidget_4)
        self.tempoCargaWeb.setEnabled(True)
        self.tempoCargaWeb.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.tempoCargaWeb.setFont(font)
        self.tempoCargaWeb.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(45,45,45);\n"
"border-radius: 3px;\n"
"")
        self.tempoCargaWeb.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.tempoCargaWeb.setPlaceholderText("Em Segundos")
        self.tempoCargaWeb.setObjectName("tempoCargaWeb")
        self.parametrosWeb.addWidget(self.tempoCargaWeb)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(245, 245, 245);")
        self.label_6.setObjectName("label_6")
        self.parametrosWeb.addWidget(self.label_6)
        self.numeroCargsWeb = QtWidgets.QTextEdit(self.verticalLayoutWidget_4)
        self.numeroCargsWeb.setEnabled(True)
        self.numeroCargsWeb.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.numeroCargsWeb.setFont(font)
        self.numeroCargsWeb.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(45,45,45);\n"
"border-radius: 3px;\n"
"")
        self.numeroCargsWeb.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.numeroCargsWeb.setPlaceholderText("Número de cargas")
        self.numeroCargsWeb.setObjectName("numeroCargsWeb")
        self.parametrosWeb.addWidget(self.numeroCargsWeb)
        self.pushButtonWeb = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonWeb.setGeometry(QtCore.QRect(70, 290, 181, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonWeb.setFont(font)
        self.pushButtonWeb.setStyleSheet("border-radius:5px;\n"
"border:1px solid rgb(255, 255, 255);")
        self.pushButtonWeb.setObjectName("pushButtonWeb")
        self.widgetWEB = QtWidgets.QWidget(self.tab_3)
        self.widgetWEB.setGeometry(QtCore.QRect(380, 50, 811, 411))
        self.widgetWEB.setObjectName("widgetWEB")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.widgetWEB)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(140, 0, 671, 411))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.webPlotLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.webPlotLayout.setContentsMargins(0, 0, 0, 0)
        self.webPlotLayout.setObjectName("webPlotLayout")
        self.escalaWEB = QtWidgets.QComboBox(self.widgetWEB)
        self.escalaWEB.setGeometry(QtCore.QRect(0, 50, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.escalaWEB.setFont(font)
        self.escalaWEB.setStyleSheet("border-top-left-radius: 10px;\n"
"color: rgb(43, 43, 43);\n"
"background-color: rgb(177, 177, 177);\n"
"")
        self.escalaWEB.setObjectName("escalaWEB")
        self.escalaWEB.addItem("")
        self.escalaWEB.addItem("")
        self.escalaWEB.addItem("")
        self.numeroCargaWEB = QtWidgets.QComboBox(self.widgetWEB)
        self.numeroCargaWEB.setGeometry(QtCore.QRect(10, 110, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.numeroCargaWEB.setFont(font)
        self.numeroCargaWEB.setStyleSheet("border-top-left-radius: 10px;\n"
"color: rgb(43, 43, 43);\n"
"background-color: rgb(177, 177, 177);\n"
"")
        self.numeroCargaWEB.setObjectName("numeroCargaWEB")
        self.analiseEstatWeb = QtWidgets.QWidget(self.tab_3)
        self.analiseEstatWeb.setGeometry(QtCore.QRect(50, 370, 221, 221))
        self.analiseEstatWeb.setObjectName("analiseEstatWeb")
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.analiseEstatWeb)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(0, 0, 221, 221))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(245,245,245);")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_3.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(245,245,245);")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_3.addWidget(self.label_21)
        self.mediaViewWEB = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.mediaViewWEB.setFont(font)
        self.mediaViewWEB.setStyleSheet("color: rgb(245,245,245)")
        self.mediaViewWEB.setObjectName("mediaViewWEB")
        self.verticalLayout_3.addWidget(self.mediaViewWEB)
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(245,245,245);")
        self.label_22.setObjectName("label_22")
        self.verticalLayout_3.addWidget(self.label_22)
        self.desvioViewWEB = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.desvioViewWEB.setFont(font)
        self.desvioViewWEB.setStyleSheet("color: rgb(245,245,245)")
        self.desvioViewWEB.setObjectName("desvioViewWEB")
        self.verticalLayout_3.addWidget(self.desvioViewWEB)
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(245,245,245);")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_3.addWidget(self.label_23)
        self.tempoTotalViewWEB = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.tempoTotalViewWEB.setFont(font)
        self.tempoTotalViewWEB.setStyleSheet("color: rgb(245,245,245)")
        self.tempoTotalViewWEB.setObjectName("tempoTotalViewWEB")
        self.verticalLayout_3.addWidget(self.tempoTotalViewWEB)
        self.label_31 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(245,245,245);")
        self.label_31.setObjectName("label_31")
        self.verticalLayout_3.addWidget(self.label_31)
        self.HurstViewWEB = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.HurstViewWEB.setFont(font)
        self.HurstViewWEB.setStyleSheet("color: rgb(245,245,245)")
        self.HurstViewWEB.setObjectName("HurstViewWEB")
        self.verticalLayout_3.addWidget(self.HurstViewWEB)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setStyleSheet("QPushButton#pushButtonIOT:pressed {\n"
"    background-color: rgba(115, 115, 115,255);\n"
"}\n"
"\n"
"QPushButton#pushButtonIOT {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.460227, y1:0, x2:0.483, y2:0.994318, stop:0.204545 rgba(115, 115, 115, 255), stop:0.755682 rgba(205, 205, 205, 255));\n"
"}\n"
"\n"
"border: 0;")
        self.tab_4.setObjectName("tab_4")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(50, 40, 281, 191))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.parametosIOT = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.parametosIOT.setContentsMargins(0, 0, 0, 0)
        self.parametosIOT.setObjectName("parametosIOT")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(245, 245, 245);")
        self.label_8.setObjectName("label_8")
        self.parametosIOT.addWidget(self.label_8)
        self.numeroDispositivos = QtWidgets.QTextEdit(self.verticalLayoutWidget_8)
        self.numeroDispositivos.setEnabled(True)
        self.numeroDispositivos.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.numeroDispositivos.setFont(font)
        self.numeroDispositivos.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(45,45,45);\n"
"border-radius: 3px;\n"
"")
        self.numeroDispositivos.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.numeroDispositivos.setPlaceholderText("Números de dispositivos IOT")
        self.numeroDispositivos.setObjectName("numeroDispositivos")
        self.parametosIOT.addWidget(self.numeroDispositivos)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(245, 245, 245);")
        self.label_9.setObjectName("label_9")
        self.parametosIOT.addWidget(self.label_9)
        self.tamanhoMensagem = QtWidgets.QTextEdit(self.verticalLayoutWidget_8)
        self.tamanhoMensagem.setEnabled(True)
        self.tamanhoMensagem.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.tamanhoMensagem.setFont(font)
        self.tamanhoMensagem.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(45,45,45);\n"
"border-radius: 3px;\n"
"")
        self.tamanhoMensagem.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.tamanhoMensagem.setPlaceholderText("Em bytes")
        self.tamanhoMensagem.setObjectName("tamanhoMensagem")
        self.parametosIOT.addWidget(self.tamanhoMensagem)
        self.label_29 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(245, 245, 245);")
        self.label_29.setObjectName("label_29")
        self.parametosIOT.addWidget(self.label_29)
        self.tempoMensagem = QtWidgets.QTextEdit(self.verticalLayoutWidget_8)
        self.tempoMensagem.setEnabled(True)
        self.tempoMensagem.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.tempoMensagem.setFont(font)
        self.tempoMensagem.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(45,45,45);\n"
"border-radius: 3px;\n"
"")
        self.tempoMensagem.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.tempoMensagem.setPlaceholderText("Em minutos")
        self.tempoMensagem.setObjectName("tempoMensagem")
        self.parametosIOT.addWidget(self.tempoMensagem)
        self.widget_4 = QtWidgets.QWidget(self.tab_4)
        self.widget_4.setGeometry(QtCore.QRect(380, 50, 811, 411))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.widget_4)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(140, 0, 671, 411))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.IOTPlotLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.IOTPlotLayout.setContentsMargins(0, 0, 0, 0)
        self.IOTPlotLayout.setObjectName("IOTPlotLayout")
        self.escalaIOT = QtWidgets.QComboBox(self.widget_4)
        self.escalaIOT.setGeometry(QtCore.QRect(10, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.escalaIOT.setFont(font)
        self.escalaIOT.setStyleSheet("border-top-left-radius: 10px;\n"
"color: rgb(43, 43, 43);\n"
"background-color: rgb(177, 177, 177);\n"
"")
        self.escalaIOT.setObjectName("escalaIOT")
        self.escalaIOT.addItem("")
        self.escalaIOT.addItem("")
        self.numeroCargaIOT = QtWidgets.QComboBox(self.widget_4)
        self.numeroCargaIOT.setGeometry(QtCore.QRect(10, 110, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.numeroCargaIOT.setFont(font)
        self.numeroCargaIOT.setStyleSheet("border-top-left-radius: 10px;\n"
"color: rgb(43, 43, 43);\n"
"background-color: rgb(177, 177, 177);\n"
"")
        self.numeroCargaIOT.setObjectName("numeroCargaIOT")
        self.pushButtonIOT = QtWidgets.QPushButton(self.tab_4)
        self.pushButtonIOT.setGeometry(QtCore.QRect(90, 310, 181, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonIOT.setFont(font)
        self.pushButtonIOT.setStyleSheet("border-radius:5px;\n"
"border:1px solid rgb(255, 255, 255);")
        self.pushButtonIOT.setObjectName("pushButtonIOT")
        self.analiseEstatIOT = QtWidgets.QWidget(self.tab_4)
        self.analiseEstatIOT.setGeometry(QtCore.QRect(70, 380, 221, 221))
        self.analiseEstatIOT.setObjectName("analiseEstatIOT")
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.analiseEstatIOT)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(0, 0, 221, 213))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(245,245,245);")
        self.label_24.setObjectName("label_24")
        self.verticalLayout_4.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(245,245,245);")
        self.label_25.setObjectName("label_25")
        self.verticalLayout_4.addWidget(self.label_25)
        self.mediaViewIOT = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.mediaViewIOT.setFont(font)
        self.mediaViewIOT.setStyleSheet("color: rgb(245,245,245)")
        self.mediaViewIOT.setObjectName("mediaViewIOT")
        self.verticalLayout_4.addWidget(self.mediaViewIOT)
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(245,245,245);")
        self.label_26.setObjectName("label_26")
        self.verticalLayout_4.addWidget(self.label_26)
        self.desvioViewIOT = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.desvioViewIOT.setFont(font)
        self.desvioViewIOT.setStyleSheet("color: rgb(245,245,245)")
        self.desvioViewIOT.setObjectName("desvioViewIOT")
        self.verticalLayout_4.addWidget(self.desvioViewIOT)
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(245,245,245);")
        self.label_27.setObjectName("label_27")
        self.verticalLayout_4.addWidget(self.label_27)
        self.tempoTotalIOT = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.tempoTotalIOT.setFont(font)
        self.tempoTotalIOT.setStyleSheet("color: rgb(245,245,245)")
        self.tempoTotalIOT.setObjectName("tempoTotalIOT")
        self.verticalLayout_4.addWidget(self.tempoTotalIOT)
        self.label_30 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(245,245,245);")
        self.label_30.setObjectName("label_30")
        self.verticalLayout_4.addWidget(self.label_30)
        self.hurstParametroIOT = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.hurstParametroIOT.setFont(font)
        self.hurstParametroIOT.setStyleSheet("color: rgb(245,245,245)")
        self.hurstParametroIOT.setObjectName("hurstParametroIOT")
        self.verticalLayout_4.addWidget(self.hurstParametroIOT)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.widget_5 = QtWidgets.QWidget(self.tab_5)
        self.widget_5.setGeometry(QtCore.QRect(190, 40, 721, 411))
        self.widget_5.setObjectName("widget_5")
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.widget_5)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(0, 0, 721, 411))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.TotalPlotLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.TotalPlotLayout.setContentsMargins(0, 0, 0, 0)
        self.TotalPlotLayout.setObjectName("TotalPlotLayout")
        self.tabWidget.addTab(self.tab_5, "")
        Gerador.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Gerador)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1217, 22))
        self.menubar.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.menubar.setObjectName("menubar")
        Gerador.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Gerador)
        self.statusbar.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.statusbar.setObjectName("statusbar")
        Gerador.setStatusBar(self.statusbar)

        self.retranslateUi(Gerador)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Gerador)

    def retranslateUi(self, Gerador):
        _translate = QtCore.QCoreApplication.translate
        Gerador.setWindowTitle(_translate("Gerador", "Gerador de Carga de Trabalho Para NS3"))
        self.pushButtonVoip.setText(_translate("Gerador", "Gerar tráfego para o NS3"))
        self.label_10.setText(_translate("Gerador", "Análise estatística"))
        self.label_11.setText(_translate("Gerador", "Média"))
        self.mediaViewVoIP.setText(_translate("Gerador", "TextLabel"))
        self.label_12.setText(_translate("Gerador", "Desvio Padrão"))
        self.desvioViewVoIP.setText(_translate("Gerador", "TextLabel"))
        self.label_13.setText(_translate("Gerador", "Tempo Total"))
        self.tempoTotalViewVoip.setText(_translate("Gerador", "TextLabel"))
        self.label_15.setText(_translate("Gerador", "Hurst"))
        self.hurstParameterVoIP.setText(_translate("Gerador", "TextLabel"))
        self.comboBox_2.setCurrentText(_translate("Gerador", "100 Milisegundos"))
        self.comboBox_2.setItemText(0, _translate("Gerador", "100 Milisegundos"))
        self.comboBox_2.setItemText(1, _translate("Gerador", "Segundos"))
        self.comboBox_2.setItemText(2, _translate("Gerador", "Minutos"))
        self.label.setText(_translate("Gerador", "Duração em segundos"))
        self.label_14.setText(_translate("Gerador", "Número de cargas"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Gerador", "Voz sobre IP"))
        self.label_2.setText(_translate("Gerador", "Codificação de vídeo"))
        self.comboBox_3.setItemText(0, _translate("Gerador", "91 Kbps"))
        self.comboBox_3.setItemText(1, _translate("Gerador", "180 Kbps"))
        self.comboBox_3.setItemText(2, _translate("Gerador", "469 Kbps"))
        self.comboBox_3.setItemText(3, _translate("Gerador", "978 Kbps"))
        self.comboBox_3.setItemText(4, _translate("Gerador", "2058 Kbps"))
        self.comboBox_3.setItemText(5, _translate("Gerador", "3953 Kbps"))
        self.comboBox_3.setItemText(6, _translate("Gerador", "9581 Kbps"))
        self.comboBox_3.setItemText(7, _translate("Gerador", "21373 Kbps"))
        self.label_3.setText(_translate("Gerador", "Tempo de vídeo"))
        self.label_5.setText(_translate("Gerador", "Número de cargas"))
        self.escalaStreamOD.setItemText(0, _translate("Gerador", "100 Milisegundos"))
        self.escalaStreamOD.setItemText(1, _translate("Gerador", "Segundos"))
        self.escalaStreamOD.setItemText(2, _translate("Gerador", "Minutos"))
        self.label_16.setText(_translate("Gerador", "Análise estatística"))
        self.label_17.setText(_translate("Gerador", "Média"))
        self.mediaViewStreamOD.setText(_translate("Gerador", "TextLabel"))
        self.label_18.setText(_translate("Gerador", "Desvio Padrão"))
        self.desvioViewStreamOD.setText(_translate("Gerador", "TextLabel"))
        self.label_19.setText(_translate("Gerador", "Tempo Total"))
        self.tempoTotalViewStreamOD.setText(_translate("Gerador", "TextLabel"))
        self.label_28.setText(_translate("Gerador", "Hurst"))
        self.hurstParameterStreamOD.setText(_translate("Gerador", "TextLabel"))
        self.pushButtonStreamOD.setText(_translate("Gerador", "Gerar tráfego para o NS3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Gerador", "Stream de Vídeo sob demanda"))
        self.label_4.setText(_translate("Gerador", "Tempo de duração"))
        self.label_6.setText(_translate("Gerador", "Número de Cargas"))
        self.pushButtonWeb.setText(_translate("Gerador", "Gerar tráfego para o NS3"))
        self.escalaWEB.setItemText(0, _translate("Gerador", "100 Milisegundos"))
        self.escalaWEB.setItemText(1, _translate("Gerador", "Segundos"))
        self.escalaWEB.setItemText(2, _translate("Gerador", "Minutos"))
        self.label_20.setText(_translate("Gerador", "Análise estatística"))
        self.label_21.setText(_translate("Gerador", "Média"))
        self.mediaViewWEB.setText(_translate("Gerador", "TextLabel"))
        self.label_22.setText(_translate("Gerador", "Desvio Padrão"))
        self.desvioViewWEB.setText(_translate("Gerador", "TextLabel"))
        self.label_23.setText(_translate("Gerador", "Tempo Total"))
        self.tempoTotalViewWEB.setText(_translate("Gerador", "TextLabel"))
        self.label_31.setText(_translate("Gerador", "Hurst"))
        self.HurstViewWEB.setText(_translate("Gerador", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Gerador", "Web"))
        self.label_8.setText(_translate("Gerador", "Número de cargas"))
        self.label_9.setText(_translate("Gerador", "Tamanho médio de mansagem"))
        self.label_29.setText(_translate("Gerador", "Tempo entre mensagem"))
        self.escalaIOT.setItemText(0, _translate("Gerador", "Minutos"))
        self.escalaIOT.setItemText(1, _translate("Gerador", "Horas"))
        self.pushButtonIOT.setText(_translate("Gerador", "Gerar tráfego para o NS3"))
        self.label_24.setText(_translate("Gerador", "Análise estatística"))
        self.label_25.setText(_translate("Gerador", "Média"))
        self.mediaViewIOT.setText(_translate("Gerador", "TextLabel"))
        self.label_26.setText(_translate("Gerador", "Desvio Padrão"))
        self.desvioViewIOT.setText(_translate("Gerador", "TextLabel"))
        self.label_27.setText(_translate("Gerador", "Tempo Total"))
        self.tempoTotalIOT.setText(_translate("Gerador", "TextLabel"))
        self.label_30.setText(_translate("Gerador", "Hurst"))
        self.hurstParametroIOT.setText(_translate("Gerador", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Gerador", "Internet das Coisas"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Gerador", "IPTV"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Gerador", "Total"))
