# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Gerador(object):
    def setupUi(self, Gerador):
        Gerador.setObjectName("Gerador")
        Gerador.resize(1217, 690)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        Gerador.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Icons/Icon_5G.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Gerador.setWindowIcon(icon)
        Gerador.setStyleSheet("background-color: rgb(45, 45, 45);")
        Gerador.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(Gerador)
        self.centralwidget.setMinimumSize(QtCore.QSize(900, 615))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1351, 741))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("border: 0;\n"
"color: rgb(238, 238, 236);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tab.setStyleSheet("QPushButton#pushButtonVoip:pressed {\n"
"    background-color: rgba(115, 115, 115,255);\n"
"}\n"
"\n"
"QPushButton#pushButtonVoip {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.460227, y1:0, x2:0.483, y2:0.994318, stop:0.204545 rgba(115, 115, 115, 255), stop:0.755682 rgba(205, 205, 205, 255));\n"
"}\n"
"\n"
"border: 0;")
        self.tab.setObjectName("tab")
        self.pushButtonVoip = QtWidgets.QPushButton(self.tab)
        self.pushButtonVoip.setGeometry(QtCore.QRect(50, 320, 181, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonVoip.setFont(font)
        self.pushButtonVoip.setStyleSheet("border-radius:5px;\n"
"border:1px solid rgb(255, 255, 255)\n"
"")
        self.pushButtonVoip.setObjectName("pushButtonVoip")
        self.analiseEstatVoIP = QtWidgets.QWidget(self.tab)
        self.analiseEstatVoIP.setGeometry(QtCore.QRect(30, 380, 231, 221))
        self.analiseEstatVoIP.setObjectName("analiseEstatVoIP")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.analiseEstatVoIP)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 231, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(245,245,245);")
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(245,245,245);")
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.mediaViewVoIP = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.mediaViewVoIP.setFont(font)
        self.mediaViewVoIP.setStyleSheet("color: rgb(245,245,245)")
        self.mediaViewVoIP.setObjectName("mediaViewVoIP")
        self.verticalLayout.addWidget(self.mediaViewVoIP)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(245,245,245);")
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.desvioViewVoIP = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.desvioViewVoIP.setFont(font)
        self.desvioViewVoIP.setStyleSheet("color: rgb(245,245,245)")
        self.desvioViewVoIP.setObjectName("desvioViewVoIP")
        self.verticalLayout.addWidget(self.desvioViewVoIP)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(245,245,245);")
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.tempoTotalViewVoip = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.tempoTotalViewVoip.setFont(font)
        self.tempoTotalViewVoip.setStyleSheet("color: rgb(245,245,245)")
        self.tempoTotalViewVoip.setObjectName("tempoTotalViewVoip")
        self.verticalLayout.addWidget(self.tempoTotalViewVoip)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(245,245,245);")
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.hurstParameterVoIP = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.hurstParameterVoIP.setFont(font)
        self.hurstParameterVoIP.setStyleSheet("color: rgb(245,245,245)")
        self.hurstParameterVoIP.setObjectName("hurstParameterVoIP")
        self.verticalLayout.addWidget(self.hurstParameterVoIP)
        self.widgetVoIPPlot = QtWidgets.QWidget(self.tab)
        self.widgetVoIPPlot.setGeometry(QtCore.QRect(290, 40, 921, 481))
        self.widgetVoIPPlot.setObjectName("widgetVoIPPlot")
        self.comboBox_2 = QtWidgets.QComboBox(self.widgetVoIPPlot)
        self.comboBox_2.setGeometry(QtCore.QRect(0, 60, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setAutoFillBackground(False)
        self.comboBox_2.setStyleSheet("border-top-left-radius: 10px;\n"
"color: rgb(43, 43, 43);\n"
"background-color: rgb(177, 177, 177);\n"
"")
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox = QtWidgets.QComboBox(self.widgetVoIPPlot)
        self.comboBox.setEnabled(True)
        self.comboBox.setGeometry(QtCore.QRect(10, 120, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.comboBox.setStyleSheet("border-top-left-radius: 10px;\n"
"background-color: rgb(177, 177, 177);\n"
"color: rgb(45, 45, 45);")
        self.comboBox.setEditable(False)
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.widgetVoIPPlot)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(140, 0, 781, 481))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.voipPlotLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.voipPlotLayout_2.setContentsMargins(0, 0, 0, 0)
        self.voipPlotLayout_2.setObjectName("voipPlotLayout_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 50, 231, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.parametroVoIP = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.parametroVoIP.setContentsMargins(0, 0, 0, 0)
        self.parametroVoIP.setObjectName("parametroVoIP")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(245, 245, 245);")
        self.label_7.setObjectName("label_7")
        self.parametroVoIP.addWidget(self.label_7)
        self.voipCodec = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voipCodec.sizePolicy().hasHeightForWidth())
        self.voipCodec.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.voipCodec.setFont(font)
        self.voipCodec.setStyleSheet("border-top-left-radius: 10px;\n"
"color: rgb(43, 43, 43);\n"
"background-color: rgb(177, 177, 177);\n"
"")
        self.voipCodec.setObjectName("voipCodec")
        self.voipCodec.addItem("")
        self.voipCodec.addItem("")
        self.voipCodec.addItem("")
        self.voipCodec.addItem("")
        self.voipCodec.addItem("")
        self.parametroVoIP.addWidget(self.voipCodec)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(245,245,245);")
        self.label.setObjectName("label")
        self.parametroVoIP.addWidget(self.label)
        self.duracao = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.duracao.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.duracao.sizePolicy().hasHeightForWidth())
        self.duracao.setSizePolicy(sizePolicy)
        self.duracao.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.duracao.setFont(font)
        self.duracao.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(45,45,45);\n"
"border-radius: 3px;\n"
"")
        self.duracao.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.duracao.setPlaceholderText("Duração")
        self.duracao.setObjectName("duracao")
        self.parametroVoIP.addWidget(self.duracao)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(245,245,245);\n"
"")
        self.label_14.setObjectName("label_14")
        self.parametroVoIP.addWidget(self.label_14)
        self.numeroCargasVoIP = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.numeroCargasVoIP.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numeroCargasVoIP.sizePolicy().hasHeightForWidth())
        self.numeroCargasVoIP.setSizePolicy(sizePolicy)
        self.numeroCargasVoIP.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.numeroCargasVoIP.setFont(font)
        self.numeroCargasVoIP.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(45, 45, 45);\n"
"border-radius: 3px;")
        self.numeroCargasVoIP.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.numeroCargasVoIP.setPlaceholderText("Digite o número de cargas")
        self.numeroCargasVoIP.setObjectName("numeroCargasVoIP")
        self.parametroVoIP.addWidget(self.numeroCargasVoIP)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("QPushButton#pushButtonStreamOD:pressed {\n"
"    background-color: rgba(115, 115, 115,255);\n"
"}\n"
"\n"
"QPushButton#pushButtonStreamOD {\n"
"    background-color: qlineargradient(spread:pad, x1:0.460227, y1:0, x2:0.483, y2:0.994318, stop:0.204545 rgba(115, 115, 115, 255), stop:0.755682 rgba(205, 205, 205, 255));\n"
"}\n"
"\n"
"border: 0;")
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(60, 30, 221, 211))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.parametrosVideo = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.parametrosVideo.setContentsMargins(0, 0, 0, 0)
        self.parametrosVideo.setObjectName("parametrosVideo")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(245, 245, 245);\n"
"")
        self.label_2.setObjectName("label_2")
        self.parametrosVideo.addWidget(self.label_2)
        self.comboBox_3 = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.comboBox_3.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("border-top-left-radius: 10px;\n"
"color: rgb(43, 43, 43);\n"
"background-color: rgb(177, 177, 177);\n"
"")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.parametrosVideo.addWidget(self.comboBox_3)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(245, 245, 245);")
        self.label_3.setObjectName("label_3")
        self.parametrosVideo.addWidget(self.label_3)
        self.tempoVideo = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.tempoVideo.setEnabled(True)
        self.tempoVideo.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.tempoVideo.setFont(font)
        self.tempoVideo.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(45,45,45);\n"
"border-radius: 3px;\n"
"")
        self.tempoVideo.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.tempoVideo.setPlaceholderText("Tempo de vídeo em segundos")
        self.tempoVideo.setObjectName("tempoVideo")
        self.parametrosVideo.addWidget(self.tempoVideo)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(245, 245, 245);\n"
"")
        self.label_5.setObjectName("label_5")
        self.parametrosVideo.addWidget(self.label_5)
        self.numeroCargas = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.numeroCargas.setEnabled(True)
        self.numeroCargas.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.numeroCargas.setFont(font)
        self.numeroCargas.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(45,45,45);\n"
"border-radius: 3px;\n"
"")
        self.numeroCargas.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.numeroCargas.setPlaceholderText("Tempo de vídeo em segundos")
        self.numeroCargas.setObjectName("numeroCargas")
        self.parametrosVideo.addWidget(self.numeroCargas)
        self.widget_2 = QtWidgets.QWidget(self.tab_2)
        self.widget_2.setGeometry(QtCore.QRect(350, 50, 811, 481))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.widget_2)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(140, 0, 671, 481))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.streamPlotLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.streamPlotLayout.setContentsMargins(0, 0, 0, 0)
        self.streamPlotLayout.setObjectName("streamPlotLayout")
        self.escalaStreamOD = QtWidgets.QComboBox(self.widget_2)
        self.escalaStreamOD.setGeometry(QtCore.QRect(0, 50, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.escalaStreamOD.setFont(font)
        self.escalaStreamOD.setStyleSheet("border-top-left-radius: 10px;\n"
"color: rgb(43, 43, 43);\n"
"background-color: rgb(177, 177, 177);\n"
"")
        self.escalaStreamOD.setObjectName("escalaStreamOD")
        self.escalaStreamOD.addItem("")
        self.escalaStreamOD.addItem("")
        self.escalaStreamOD.addItem("")
        self.numeroCarga = QtWidgets.QComboBox(self.widget_2)
        self.numeroCarga.setGeometry(QtCore.QRect(10, 110, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.numeroCarga.setFont(font)
        self.numeroCarga.setStyleSheet("border-top-left-radius: 10px;\n"
"color: rgb(43, 43, 43);\n"
"background-color: rgb(177, 177, 177);\n"
"")
        self.numeroCarga.setObjectName("numeroCarga")
        self.analiseEstatStreamOD = QtWidgets.QWidget(self.tab_2)
        self.analiseEstatStreamOD.setGeometry(QtCore.QRect(60, 320, 221, 221))
        self.analiseEstatStreamOD.setObjectName("analiseEstatStreamOD")
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.analiseEstatStreamOD)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(0, 0, 221, 221))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(245,245,245);")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(245,245,245);")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.mediaViewStreamOD = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.mediaViewStreamOD.setFont(font)
        self.mediaViewStreamOD.setStyleSheet("color: rgb(245,245,245)")
        self.mediaViewStreamOD.setObjectName("mediaViewStreamOD")
        self.verticalLayout_2.addWidget(self.mediaViewStreamOD)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(245,245,245);")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_2.addWidget(self.label_18)
        self.desvioViewStreamOD = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.desvioViewStreamOD.setFont(font)
        self.desvioViewStreamOD.setStyleSheet("color: rgb(245,245,245)")
        self.desvioViewStreamOD.setObjectName("desvioViewStreamOD")
        self.verticalLayout_2.addWidget(self.desvioViewStreamOD)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(245,245,245);")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.tempoTotalViewStreamOD = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.tempoTotalViewStreamOD.setFont(font)
        self.tempoTotalViewStreamOD.setStyleSheet("color: rgb(245,245,245)")
        self.tempoTotalViewStreamOD.setObjectName("tempoTotalViewStreamOD")
        self.verticalLayout_2.addWidget(self.tempoTotalViewStreamOD)
        self.label_28 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(245,245,245);")
        self.label_28.setObjectName("label_28")
        self.verticalLayout_2.addWidget(self.label_28)
        self.hurstParameterStreamOD = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.hurstParameterStreamOD.setFont(font)
        self.hurstParameterStreamOD.setStyleSheet("color: rgb(245,245,245)")
        self.hurstParameterStreamOD.setObjectName("hurstParameterStreamOD")
        self.verticalLayout_2.addWidget(self.hurstParameterStreamOD)
        self.pushButtonStreamOD = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonStreamOD.setGeometry(QtCore.QRect(70, 260, 181, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonStreamOD.setFont(font)
        self.pushButtonStreamOD.setStyleSheet("border-radius:5px;\n"
"border:1px solid rgb(255, 255, 255);")
        self.pushButtonStreamOD.setObjectName("pushButtonStreamOD")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tab_3.setFont(font)
        self.tab_3.setStyleSheet("QPushButton#pushButtonWeb:pressed {\n"
"    background-color: rgba(115, 115, 115,255);\n"
"}\n"
"\n"
"QPushButton#pushButtonWeb {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.460227, y1:0, x2:0.483, y2:0.994318, stop:0.204545 rgba(115, 115, 115, 255), stop:0.755682 rgba(205, 205, 205, 255));\n"
"}\n"
"\n"
"border: 0;")
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(40, 50, 261, 151))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.parametrosWeb = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.parametrosWeb.setContentsMargins(0, 0, 0, 0)
        self.parametrosWeb.setObjectName("parametrosWeb")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(245, 245, 245);")
        self.label_4.setObjectName("label_4")
        self.parametrosWeb.addWidget(self.label_4)
        self.tempoCargaWeb = QtWidgets.QTextEdit(self.verticalLayoutWidget_4)
        self.tempoCargaWeb.setEnabled(True)
        self.tempoCargaWeb.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.tempoCargaWeb.setFont(font)
        self.tempoCargaWeb.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(45,45,45);\n"
"border-radius: 3px;\n"
"")
        self.tempoCargaWeb.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.tempoCargaWeb.setPlaceholderText("Em Segundos")
        self.tempoCargaWeb.setObjectName("tempoCargaWeb")
        self.parametrosWeb.addWidget(self.tempoCargaWeb)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(245, 245, 245);")
        self.label_6.setObjectName("label_6")
        self.parametrosWeb.addWidget(self.label_6)
        self.numeroCargsWeb = QtWidgets.QTextEdit(self.verticalLayoutWidget_4)
        self.numeroCargsWeb.setEnabled(True)
        self.numeroCargsWeb.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.numeroCargsWeb.setFont(font)
        self.numeroCargsWeb.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(45,45,45);\n"
"border-radius: 3px;\n"
"")
        self.numeroCargsWeb.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.numeroCargsWeb.setPlaceholderText("Número de cargas")
        self.numeroCargsWeb.setObjectName("numeroCargsWeb")
        self.parametrosWeb.addWidget(self.numeroCargsWeb)
        self.pushButtonWeb = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonWeb.setGeometry(QtCore.QRect(70, 290, 181, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonWeb.setFont(font)
        self.pushButtonWeb.setStyleSheet("border-radius:5px;\n"
"border:1px solid rgb(255, 255, 255);")
        self.pushButtonWeb.setObjectName("pushButtonWeb")
        self.widgetWEB = QtWidgets.QWidget(self.tab_3)
        self.widgetWEB.setGeometry(QtCore.QRect(380, 50, 811, 411))
        self.widgetWEB.setObjectName("widgetWEB")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.widgetWEB)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(140, 0, 671, 411))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.webPlotLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.webPlotLayout.setContentsMargins(0, 0, 0, 0)
        self.webPlotLayout.setObjectName("webPlotLayout")
        self.escalaWEB = QtWidgets.QComboBox(self.widgetWEB)
        self.escalaWEB.setGeometry(QtCore.QRect(0, 50, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.escalaWEB.setFont(font)
        self.escalaWEB.setStyleSheet("border-top-left-radius: 10px;\n"
"color: rgb(43, 43, 43);\n"
"background-color: rgb(177, 177, 177);\n"
"")
        self.escalaWEB.setObjectName("escalaWEB")
        self.escalaWEB.addItem("")
        self.escalaWEB.addItem("")
        self.escalaWEB.addItem("")
        self.numeroCargaWEB = QtWidgets.QComboBox(self.widgetWEB)
        self.numeroCargaWEB.setGeometry(QtCore.QRect(10, 110, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.numeroCargaWEB.setFont(font)
        self.numeroCargaWEB.setStyleSheet("border-top-left-radius: 10px;\n"
"color: rgb(43, 43, 43);\n"
"background-color: rgb(177, 177, 177);\n"
"")
        self.numeroCargaWEB.setObjectName("numeroCargaWEB")
        self.analiseEstatWeb = QtWidgets.QWidget(self.tab_3)
        self.analiseEstatWeb.setGeometry(QtCore.QRect(60, 350, 221, 221))
        self.analiseEstatWeb.setObjectName("analiseEstatWeb")
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.analiseEstatWeb)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(0, 0, 221, 221))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(245,245,245);")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_3.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(245,245,245);")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_3.addWidget(self.label_21)
        self.mediaViewWEB = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.mediaViewWEB.setFont(font)
        self.mediaViewWEB.setStyleSheet("color: rgb(245,245,245)")
        self.mediaViewWEB.setObjectName("mediaViewWEB")
        self.verticalLayout_3.addWidget(self.mediaViewWEB)
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(245,245,245);")
        self.label_22.setObjectName("label_22")
        self.verticalLayout_3.addWidget(self.label_22)
        self.desvioViewWEB = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.desvioViewWEB.setFont(font)
        self.desvioViewWEB.setStyleSheet("color: rgb(245,245,245)")
        self.desvioViewWEB.setObjectName("desvioViewWEB")
        self.verticalLayout_3.addWidget(self.desvioViewWEB)
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(245,245,245);")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_3.addWidget(self.label_23)
        self.tempoTotalViewWEB = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.tempoTotalViewWEB.setFont(font)
        self.tempoTotalViewWEB.setStyleSheet("color: rgb(245,245,245)")
        self.tempoTotalViewWEB.setObjectName("tempoTotalViewWEB")
        self.verticalLayout_3.addWidget(self.tempoTotalViewWEB)
        self.label_31 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(245,245,245);")
        self.label_31.setObjectName("label_31")
        self.verticalLayout_3.addWidget(self.label_31)
        self.HurstViewWEB = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.HurstViewWEB.setFont(font)
        self.HurstViewWEB.setStyleSheet("color: rgb(245,245,245)")
        self.HurstViewWEB.setObjectName("HurstViewWEB")
        self.verticalLayout_3.addWidget(self.HurstViewWEB)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setStyleSheet("QPushButton#pushButtonIOT:pressed {\n"
"    background-color: rgba(115, 115, 115,255);\n"
"}\n"
"\n"
"QPushButton#pushButtonIOT {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.460227, y1:0, x2:0.483, y2:0.994318, stop:0.204545 rgba(115, 115, 115, 255), stop:0.755682 rgba(205, 205, 205, 255));\n"
"}\n"
"\n"
"border: 0;")
        self.tab_4.setObjectName("tab_4")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(29, 20, 331, 301))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.parametosIOT = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.parametosIOT.setContentsMargins(0, 0, 0, 0)
        self.parametosIOT.setObjectName("parametosIOT")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(245, 245, 245);")
        self.label_8.setObjectName("label_8")
        self.parametosIOT.addWidget(self.label_8)
        self.numeroDispositivos = QtWidgets.QTextEdit(self.verticalLayoutWidget_8)
        self.numeroDispositivos.setEnabled(True)
        self.numeroDispositivos.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.numeroDispositivos.setFont(font)
        self.numeroDispositivos.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(45,45,45);\n"
"border-radius: 3px;\n"
"")
        self.numeroDispositivos.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.numeroDispositivos.setPlaceholderText("Números de dispositivos IOT")
        self.numeroDispositivos.setObjectName("numeroDispositivos")
        self.parametosIOT.addWidget(self.numeroDispositivos)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(245, 245, 245);")
        self.label_9.setObjectName("label_9")
        self.parametosIOT.addWidget(self.label_9)
        self.tamanhoMensagem = QtWidgets.QTextEdit(self.verticalLayoutWidget_8)
        self.tamanhoMensagem.setEnabled(True)
        self.tamanhoMensagem.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.tamanhoMensagem.setFont(font)
        self.tamanhoMensagem.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(45,45,45);\n"
"border-radius: 3px;\n"
"")
        self.tamanhoMensagem.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.tamanhoMensagem.setPlaceholderText("Em bytes")
        self.tamanhoMensagem.setObjectName("tamanhoMensagem")
        self.parametosIOT.addWidget(self.tamanhoMensagem)
        self.label_29 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(245, 245, 245);")
        self.label_29.setObjectName("label_29")
        self.parametosIOT.addWidget(self.label_29)
        self.periodoMensagem = QtWidgets.QTextEdit(self.verticalLayoutWidget_8)
        self.periodoMensagem.setEnabled(True)
        self.periodoMensagem.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.periodoMensagem.setFont(font)
        self.periodoMensagem.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(45,45,45);\n"
"border-radius: 3px;\n"
"")
        self.periodoMensagem.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.periodoMensagem.setPlaceholderText("Em segundos")
        self.periodoMensagem.setObjectName("periodoMensagem")
        self.parametosIOT.addWidget(self.periodoMensagem)
        self.label_36 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color: rgb(245, 245, 245);")
        self.label_36.setObjectName("label_36")
        self.parametosIOT.addWidget(self.label_36)
        self.tempoMensagem = QtWidgets.QTextEdit(self.verticalLayoutWidget_8)
        self.tempoMensagem.setEnabled(True)
        self.tempoMensagem.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.tempoMensagem.setFont(font)
        self.tempoMensagem.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(45,45,45);\n"
"border-radius: 3px;\n"
"")
        self.tempoMensagem.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.tempoMensagem.setPlaceholderText("Em segundos")
        self.tempoMensagem.setObjectName("tempoMensagem")
        self.parametosIOT.addWidget(self.tempoMensagem)
        self.label_46 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("color: rgb(245, 245, 245);")
        self.label_46.setObjectName("label_46")
        self.parametosIOT.addWidget(self.label_46)
        self.numeroCargasIOT = QtWidgets.QTextEdit(self.verticalLayoutWidget_8)
        self.numeroCargasIOT.setEnabled(True)
        self.numeroCargasIOT.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.numeroCargasIOT.setFont(font)
        self.numeroCargasIOT.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(45,45,45);\n"
"border-radius: 3px;\n"
"")
        self.numeroCargasIOT.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.numeroCargasIOT.setPlaceholderText("Número de cargas")
        self.numeroCargasIOT.setObjectName("numeroCargasIOT")
        self.parametosIOT.addWidget(self.numeroCargasIOT)
        self.widget_4 = QtWidgets.QWidget(self.tab_4)
        self.widget_4.setGeometry(QtCore.QRect(380, 50, 811, 411))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.widget_4)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(140, 0, 671, 411))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.IOTPlotLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.IOTPlotLayout.setContentsMargins(0, 0, 0, 0)
        self.IOTPlotLayout.setObjectName("IOTPlotLayout")
        self.escalaIOT = QtWidgets.QComboBox(self.widget_4)
        self.escalaIOT.setGeometry(QtCore.QRect(10, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.escalaIOT.setFont(font)
        self.escalaIOT.setStyleSheet("border-top-left-radius: 10px;\n"
"color: rgb(43, 43, 43);\n"
"background-color: rgb(177, 177, 177);\n"
"")
        self.escalaIOT.setObjectName("escalaIOT")
        self.escalaIOT.addItem("")
        self.escalaIOT.addItem("")
        self.numeroCargaIOT = QtWidgets.QComboBox(self.widget_4)
        self.numeroCargaIOT.setGeometry(QtCore.QRect(10, 110, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.numeroCargaIOT.setFont(font)
        self.numeroCargaIOT.setStyleSheet("border-top-left-radius: 10px;\n"
"color: rgb(43, 43, 43);\n"
"background-color: rgb(177, 177, 177);\n"
"")
        self.numeroCargaIOT.setObjectName("numeroCargaIOT")
        self.pushButtonIOT = QtWidgets.QPushButton(self.tab_4)
        self.pushButtonIOT.setGeometry(QtCore.QRect(90, 340, 181, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonIOT.setFont(font)
        self.pushButtonIOT.setStyleSheet("border-radius:5px;\n"
"border:1px solid rgb(255, 255, 255);")
        self.pushButtonIOT.setObjectName("pushButtonIOT")
        self.analiseEstatIOT = QtWidgets.QWidget(self.tab_4)
        self.analiseEstatIOT.setGeometry(QtCore.QRect(70, 400, 221, 221))
        self.analiseEstatIOT.setObjectName("analiseEstatIOT")
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.analiseEstatIOT)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(0, 0, 221, 213))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(245,245,245);")
        self.label_24.setObjectName("label_24")
        self.verticalLayout_4.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(245,245,245);")
        self.label_25.setObjectName("label_25")
        self.verticalLayout_4.addWidget(self.label_25)
        self.mediaViewIOT = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.mediaViewIOT.setFont(font)
        self.mediaViewIOT.setStyleSheet("color: rgb(245,245,245)")
        self.mediaViewIOT.setObjectName("mediaViewIOT")
        self.verticalLayout_4.addWidget(self.mediaViewIOT)
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(245,245,245);")
        self.label_26.setObjectName("label_26")
        self.verticalLayout_4.addWidget(self.label_26)
        self.desvioViewIOT = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.desvioViewIOT.setFont(font)
        self.desvioViewIOT.setStyleSheet("color: rgb(245,245,245)")
        self.desvioViewIOT.setObjectName("desvioViewIOT")
        self.verticalLayout_4.addWidget(self.desvioViewIOT)
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(245,245,245);")
        self.label_27.setObjectName("label_27")
        self.verticalLayout_4.addWidget(self.label_27)
        self.tempoTotalIOT = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.tempoTotalIOT.setFont(font)
        self.tempoTotalIOT.setStyleSheet("color: rgb(245,245,245)")
        self.tempoTotalIOT.setObjectName("tempoTotalIOT")
        self.verticalLayout_4.addWidget(self.tempoTotalIOT)
        self.label_30 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(245,245,245);")
        self.label_30.setObjectName("label_30")
        self.verticalLayout_4.addWidget(self.label_30)
        self.hurstParametroIOT = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.hurstParametroIOT.setFont(font)
        self.hurstParametroIOT.setStyleSheet("color: rgb(245,245,245)")
        self.hurstParametroIOT.setObjectName("hurstParametroIOT")
        self.verticalLayout_4.addWidget(self.hurstParametroIOT)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setStyleSheet("QPushButton#pushButtonTotal:pressed {\n"
"    background-color: rgba(115, 115, 115,255);\n"
"}\n"
"\n"
"QPushButton#pushButtonTotal {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.460227, y1:0, x2:0.483, y2:0.994318, stop:0.204545 rgba(115, 115, 115, 255), stop:0.755682 rgba(205, 205, 205, 255));\n"
"}\n"
"\n"
"border: 0;")
        self.tab_5.setObjectName("tab_5")
        self.totalPlotWidget = QtWidgets.QWidget(self.tab_5)
        self.totalPlotWidget.setGeometry(QtCore.QRect(480, 30, 721, 411))
        self.totalPlotWidget.setObjectName("totalPlotWidget")
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.totalPlotWidget)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(0, 0, 721, 411))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.TotalPlotLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.TotalPlotLayout.setContentsMargins(0, 0, 0, 0)
        self.TotalPlotLayout.setObjectName("TotalPlotLayout")
        self.pushButtonTotal = QtWidgets.QPushButton(self.tab_5)
        self.pushButtonTotal.setGeometry(QtCore.QRect(150, 290, 181, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonTotal.setFont(font)
        self.pushButtonTotal.setStyleSheet("border-radius:5px;\n"
"border:1px solid rgb(255, 255, 255);")
        self.pushButtonTotal.setObjectName("pushButtonTotal")
        self.voipTotalParam = QtWidgets.QWidget(self.tab_5)
        self.voipTotalParam.setGeometry(QtCore.QRect(90, 30, 281, 161))
        self.voipTotalParam.setObjectName("voipTotalParam")
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.voipTotalParam)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(0, 0, 281, 161))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_32 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_32.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color: rgb(245, 245, 245);")
        self.label_32.setObjectName("label_32")
        self.verticalLayout_5.addWidget(self.label_32)
        self.label_33 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_33.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(245, 245, 245);")
        self.label_33.setObjectName("label_33")
        self.verticalLayout_5.addWidget(self.label_33)
        self.tempoInicialTotal = QtWidgets.QTextEdit(self.verticalLayoutWidget_14)
        self.tempoInicialTotal.setEnabled(True)
        self.tempoInicialTotal.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.tempoInicialTotal.setFont(font)
        self.tempoInicialTotal.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(45,45,45);\n"
"border-radius: 3px;\n"
"")
        self.tempoInicialTotal.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.tempoInicialTotal.setPlaceholderText("Tempo Inicial")
        self.tempoInicialTotal.setObjectName("tempoInicialTotal")
        self.verticalLayout_5.addWidget(self.tempoInicialTotal)
        self.label_34 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_34.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(245, 245, 245);")
        self.label_34.setObjectName("label_34")
        self.verticalLayout_5.addWidget(self.label_34)
        self.tempoFinalTotal = QtWidgets.QTextEdit(self.verticalLayoutWidget_14)
        self.tempoFinalTotal.setEnabled(True)
        self.tempoFinalTotal.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.tempoFinalTotal.setFont(font)
        self.tempoFinalTotal.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(45,45,45);\n"
"border-radius: 3px;\n"
"")
        self.tempoFinalTotal.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.tempoFinalTotal.setPlaceholderText("Tempo Final")
        self.tempoFinalTotal.setObjectName("tempoFinalTotal")
        self.verticalLayout_5.addWidget(self.tempoFinalTotal)
        self.analiseEstatTotal = QtWidgets.QWidget(self.tab_5)
        self.analiseEstatTotal.setGeometry(QtCore.QRect(130, 370, 221, 221))
        self.analiseEstatTotal.setObjectName("analiseEstatTotal")
        self.verticalLayoutWidget_18 = QtWidgets.QWidget(self.analiseEstatTotal)
        self.verticalLayoutWidget_18.setGeometry(QtCore.QRect(0, 0, 221, 213))
        self.verticalLayoutWidget_18.setObjectName("verticalLayoutWidget_18")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_18)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_37 = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color: rgb(245,245,245);")
        self.label_37.setObjectName("label_37")
        self.verticalLayout_9.addWidget(self.label_37)
        self.mediaTotalView = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.mediaTotalView.setFont(font)
        self.mediaTotalView.setStyleSheet("color: rgb(245,245,245)")
        self.mediaTotalView.setObjectName("mediaTotalView")
        self.verticalLayout_9.addWidget(self.mediaTotalView)
        self.label_38 = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("color: rgb(245,245,245);")
        self.label_38.setObjectName("label_38")
        self.verticalLayout_9.addWidget(self.label_38)
        self.desvioTotalView = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.desvioTotalView.setFont(font)
        self.desvioTotalView.setStyleSheet("color: rgb(245,245,245)")
        self.desvioTotalView.setObjectName("desvioTotalView")
        self.verticalLayout_9.addWidget(self.desvioTotalView)
        self.label_39 = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color: rgb(245,245,245);")
        self.label_39.setObjectName("label_39")
        self.verticalLayout_9.addWidget(self.label_39)
        self.tempoTotalView = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.tempoTotalView.setFont(font)
        self.tempoTotalView.setStyleSheet("color: rgb(245,245,245)")
        self.tempoTotalView.setObjectName("tempoTotalView")
        self.verticalLayout_9.addWidget(self.tempoTotalView)
        self.label_40 = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("color: rgb(245,245,245);")
        self.label_40.setObjectName("label_40")
        self.verticalLayout_9.addWidget(self.label_40)
        self.hurstTotalView = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.hurstTotalView.setFont(font)
        self.hurstTotalView.setStyleSheet("color: rgb(245,245,245)")
        self.hurstTotalView.setObjectName("hurstTotalView")
        self.verticalLayout_9.addWidget(self.hurstTotalView)
        self.widget = QtWidgets.QWidget(self.tab_5)
        self.widget.setGeometry(QtCore.QRect(480, 470, 701, 121))
        self.widget.setObjectName("widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 701, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_47 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("color: rgb(245,245,245)")
        self.label_47.setText("")
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_7.addWidget(self.label_47)
        self.label_48 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("color: rgb(245,245,245)")
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_7.addWidget(self.label_48)
        self.label_35 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(245,245,245)")
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_7.addWidget(self.label_35)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_42 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("color: rgb(245,245,245);")
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_6.addWidget(self.label_42)
        self.percentTotal = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.percentTotal.setFont(font)
        self.percentTotal.setStyleSheet("color: rgb(245,245,245)")
        self.percentTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.percentTotal.setObjectName("percentTotal")
        self.verticalLayout_6.addWidget(self.percentTotal)
        self.bytesTotal = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.bytesTotal.setFont(font)
        self.bytesTotal.setStyleSheet("color: rgb(245,245,245)")
        self.bytesTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.bytesTotal.setObjectName("bytesTotal")
        self.verticalLayout_6.addWidget(self.bytesTotal)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_41 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("color: rgb(245,245,245);")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_8.addWidget(self.label_41)
        self.percentVoip = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.percentVoip.setFont(font)
        self.percentVoip.setStyleSheet("color: rgb(245,245,245)")
        self.percentVoip.setAlignment(QtCore.Qt.AlignCenter)
        self.percentVoip.setObjectName("percentVoip")
        self.verticalLayout_8.addWidget(self.percentVoip)
        self.byteVoip = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.byteVoip.setFont(font)
        self.byteVoip.setStyleSheet("color: rgb(245,245,245)")
        self.byteVoip.setAlignment(QtCore.Qt.AlignCenter)
        self.byteVoip.setObjectName("byteVoip")
        self.verticalLayout_8.addWidget(self.byteVoip)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_43 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("color: rgb(245,245,245);")
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_10.addWidget(self.label_43)
        self.percentVoD = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.percentVoD.setFont(font)
        self.percentVoD.setStyleSheet("color: rgb(245,245,245)")
        self.percentVoD.setAlignment(QtCore.Qt.AlignCenter)
        self.percentVoD.setObjectName("percentVoD")
        self.verticalLayout_10.addWidget(self.percentVoD)
        self.bytesVoD = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.bytesVoD.setFont(font)
        self.bytesVoD.setStyleSheet("color: rgb(245,245,245)")
        self.bytesVoD.setAlignment(QtCore.Qt.AlignCenter)
        self.bytesVoD.setObjectName("bytesVoD")
        self.verticalLayout_10.addWidget(self.bytesVoD)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_44 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("color: rgb(245,245,245);")
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_11.addWidget(self.label_44)
        self.percentWeb = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.percentWeb.setFont(font)
        self.percentWeb.setStyleSheet("color: rgb(245,245,245)")
        self.percentWeb.setAlignment(QtCore.Qt.AlignCenter)
        self.percentWeb.setObjectName("percentWeb")
        self.verticalLayout_11.addWidget(self.percentWeb)
        self.bytesWeb = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.bytesWeb.setFont(font)
        self.bytesWeb.setStyleSheet("color: rgb(245,245,245)")
        self.bytesWeb.setAlignment(QtCore.Qt.AlignCenter)
        self.bytesWeb.setObjectName("bytesWeb")
        self.verticalLayout_11.addWidget(self.bytesWeb)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_45 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("color: rgb(245,245,245);")
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_12.addWidget(self.label_45)
        self.percentIOT = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.percentIOT.setFont(font)
        self.percentIOT.setStyleSheet("color: rgb(245,245,245)")
        self.percentIOT.setAlignment(QtCore.Qt.AlignCenter)
        self.percentIOT.setObjectName("percentIOT")
        self.verticalLayout_12.addWidget(self.percentIOT)
        self.bytesIOT = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.bytesIOT.setFont(font)
        self.bytesIOT.setStyleSheet("color: rgb(245,245,245)")
        self.bytesIOT.setAlignment(QtCore.Qt.AlignCenter)
        self.bytesIOT.setObjectName("bytesIOT")
        self.verticalLayout_12.addWidget(self.bytesIOT)
        self.horizontalLayout.addLayout(self.verticalLayout_12)
        self.tabWidget.addTab(self.tab_5, "")
        Gerador.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Gerador)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1217, 22))
        self.menubar.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.menubar.setObjectName("menubar")
        Gerador.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Gerador)
        self.statusbar.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.statusbar.setObjectName("statusbar")
        Gerador.setStatusBar(self.statusbar)

        self.retranslateUi(Gerador)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Gerador)

    def retranslateUi(self, Gerador):
        _translate = QtCore.QCoreApplication.translate
        Gerador.setWindowTitle(_translate("Gerador", "Gerador de Carga de Trabalho Para NS3"))
        self.pushButtonVoip.setText(_translate("Gerador", "Gerar tráfego"))
        self.label_10.setText(_translate("Gerador", "Análise estatística"))
        self.label_11.setText(_translate("Gerador", "Média"))
        self.mediaViewVoIP.setText(_translate("Gerador", "TextLabel"))
        self.label_12.setText(_translate("Gerador", "Desvio Padrão"))
        self.desvioViewVoIP.setText(_translate("Gerador", "TextLabel"))
        self.label_13.setText(_translate("Gerador", "Tempo Total"))
        self.tempoTotalViewVoip.setText(_translate("Gerador", "TextLabel"))
        self.label_15.setText(_translate("Gerador", "Hurst"))
        self.hurstParameterVoIP.setText(_translate("Gerador", "TextLabel"))
        self.comboBox_2.setCurrentText(_translate("Gerador", "100 Milisegundos"))
        self.comboBox_2.setItemText(0, _translate("Gerador", "100 Milisegundos"))
        self.comboBox_2.setItemText(1, _translate("Gerador", "Segundos"))
        self.comboBox_2.setItemText(2, _translate("Gerador", "Minutos"))
        self.label_7.setText(_translate("Gerador", "CODEC"))
        self.voipCodec.setItemText(0, _translate("Gerador", "G.729 (CBR: 8 kbps) "))
        self.voipCodec.setItemText(1, _translate("Gerador", "G.729 (CBR: 6.4 kbps) "))
        self.voipCodec.setItemText(2, _translate("Gerador", "G.711 A-Law"))
        self.voipCodec.setItemText(3, _translate("Gerador", "SILK (VBR)"))
        self.voipCodec.setItemText(4, _translate("Gerador", "iSAC (VBR)"))
        self.label.setText(_translate("Gerador", "Duração em segundos"))
        self.label_14.setText(_translate("Gerador", "Número de cargas"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Gerador", "Voz sobre IP"))
        self.label_2.setText(_translate("Gerador", "Codificação de vídeo"))
        self.comboBox_3.setItemText(0, _translate("Gerador", "91 Kbps"))
        self.comboBox_3.setItemText(1, _translate("Gerador", "180 Kbps"))
        self.comboBox_3.setItemText(2, _translate("Gerador", "469 Kbps"))
        self.comboBox_3.setItemText(3, _translate("Gerador", "978 Kbps"))
        self.comboBox_3.setItemText(4, _translate("Gerador", "2058 Kbps"))
        self.comboBox_3.setItemText(5, _translate("Gerador", "3953 Kbps"))
        self.comboBox_3.setItemText(6, _translate("Gerador", "9581 Kbps"))
        self.comboBox_3.setItemText(7, _translate("Gerador", "21373 Kbps"))
        self.label_3.setText(_translate("Gerador", "Tempo de vídeo"))
        self.label_5.setText(_translate("Gerador", "Número de cargas"))
        self.escalaStreamOD.setItemText(0, _translate("Gerador", "100 Milisegundos"))
        self.escalaStreamOD.setItemText(1, _translate("Gerador", "Segundos"))
        self.escalaStreamOD.setItemText(2, _translate("Gerador", "Minutos"))
        self.label_16.setText(_translate("Gerador", "Análise estatística"))
        self.label_17.setText(_translate("Gerador", "Média"))
        self.mediaViewStreamOD.setText(_translate("Gerador", "TextLabel"))
        self.label_18.setText(_translate("Gerador", "Desvio Padrão"))
        self.desvioViewStreamOD.setText(_translate("Gerador", "TextLabel"))
        self.label_19.setText(_translate("Gerador", "Tempo Total"))
        self.tempoTotalViewStreamOD.setText(_translate("Gerador", "TextLabel"))
        self.label_28.setText(_translate("Gerador", "Hurst"))
        self.hurstParameterStreamOD.setText(_translate("Gerador", "TextLabel"))
        self.pushButtonStreamOD.setText(_translate("Gerador", "Gerar tráfego"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Gerador", "Stream de Vídeo sob demanda"))
        self.label_4.setText(_translate("Gerador", "Tempo de duração"))
        self.label_6.setText(_translate("Gerador", "Número de Cargas"))
        self.pushButtonWeb.setText(_translate("Gerador", "Gerar tráfego"))
        self.escalaWEB.setItemText(0, _translate("Gerador", "100 Milisegundos"))
        self.escalaWEB.setItemText(1, _translate("Gerador", "Segundos"))
        self.escalaWEB.setItemText(2, _translate("Gerador", "Minutos"))
        self.label_20.setText(_translate("Gerador", "Análise estatística"))
        self.label_21.setText(_translate("Gerador", "Média"))
        self.mediaViewWEB.setText(_translate("Gerador", "TextLabel"))
        self.label_22.setText(_translate("Gerador", "Desvio Padrão"))
        self.desvioViewWEB.setText(_translate("Gerador", "TextLabel"))
        self.label_23.setText(_translate("Gerador", "Tempo Total"))
        self.tempoTotalViewWEB.setText(_translate("Gerador", "TextLabel"))
        self.label_31.setText(_translate("Gerador", "Hurst"))
        self.HurstViewWEB.setText(_translate("Gerador", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Gerador", "Web"))
        self.label_8.setText(_translate("Gerador", "Número de dispositivos"))
        self.label_9.setText(_translate("Gerador", "Tamanho da mansagem"))
        self.label_29.setText(_translate("Gerador", "Período individual de transmissão"))
        self.label_36.setText(_translate("Gerador", "Tempo total"))
        self.label_46.setText(_translate("Gerador", "Número de Cargas"))
        self.escalaIOT.setItemText(0, _translate("Gerador", "Segundos"))
        self.escalaIOT.setItemText(1, _translate("Gerador", "Minutos"))
        self.pushButtonIOT.setText(_translate("Gerador", "Gerar tráfego"))
        self.label_24.setText(_translate("Gerador", "Análise estatística"))
        self.label_25.setText(_translate("Gerador", "Média"))
        self.mediaViewIOT.setText(_translate("Gerador", "TextLabel"))
        self.label_26.setText(_translate("Gerador", "Desvio Padrão"))
        self.desvioViewIOT.setText(_translate("Gerador", "TextLabel"))
        self.label_27.setText(_translate("Gerador", "Tempo Total"))
        self.tempoTotalIOT.setText(_translate("Gerador", "TextLabel"))
        self.label_30.setText(_translate("Gerador", "Hurst"))
        self.hurstParametroIOT.setText(_translate("Gerador", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Gerador", "Internet das Coisas"))
        self.pushButtonTotal.setText(_translate("Gerador", "Analisar Carga"))
        self.label_32.setText(_translate("Gerador", "Escolha um período"))
        self.label_33.setText(_translate("Gerador", "Início"))
        self.label_34.setText(_translate("Gerador", "Fim"))
        self.label_37.setText(_translate("Gerador", "Média"))
        self.mediaTotalView.setText(_translate("Gerador", "TextLabel"))
        self.label_38.setText(_translate("Gerador", "Desvio Padrão"))
        self.desvioTotalView.setText(_translate("Gerador", "TextLabel"))
        self.label_39.setText(_translate("Gerador", "Tempo Total"))
        self.tempoTotalView.setText(_translate("Gerador", "TextLabel"))
        self.label_40.setText(_translate("Gerador", "Hurst"))
        self.hurstTotalView.setText(_translate("Gerador", "TextLabel"))
        self.label_48.setText(_translate("Gerador", "Porcentagem"))
        self.label_35.setText(_translate("Gerador", "Bytes"))
        self.label_42.setText(_translate("Gerador", "Total"))
        self.percentTotal.setText(_translate("Gerador", "TextLabel"))
        self.bytesTotal.setText(_translate("Gerador", "TextLabel"))
        self.label_41.setText(_translate("Gerador", "VoIP"))
        self.percentVoip.setText(_translate("Gerador", "TextLabel"))
        self.byteVoip.setText(_translate("Gerador", "TextLabel"))
        self.label_43.setText(_translate("Gerador", "VoD"))
        self.percentVoD.setText(_translate("Gerador", "TextLabel"))
        self.bytesVoD.setText(_translate("Gerador", "TextLabel"))
        self.label_44.setText(_translate("Gerador", "Web"))
        self.percentWeb.setText(_translate("Gerador", "TextLabel"))
        self.bytesWeb.setText(_translate("Gerador", "TextLabel"))
        self.label_45.setText(_translate("Gerador", "IOT"))
        self.percentIOT.setText(_translate("Gerador", "TextLabel"))
        self.bytesIOT.setText(_translate("Gerador", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Gerador", "Total"))
